#!/bin/sh
set -e

WORKER_PWD="$(cat /run/secrets/user_pwd)"
READONLY_PWD="$(cat /run/secrets/readonly_pwd)"

# escape single quotes for SQL literals:  '  ->  ''
WORKER_PWD_SQL=$(printf "%s" "$WORKER_PWD" | sed "s/'/''/g")
READONLY_PWD_SQL=$(printf "%s" "$READONLY_PWD" | sed "s/'/''/g")

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
REVOKE ALL ON DATABASE apidb FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'worker') THEN
    CREATE ROLE worker LOGIN PASSWORD '${WORKER_PWD_SQL}';
  ELSE
    ALTER ROLE worker WITH LOGIN PASSWORD '${WORKER_PWD_SQL}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'readonly') THEN
    CREATE ROLE readonly LOGIN PASSWORD '${READONLY_PWD_SQL}';
  ELSE
    ALTER ROLE readonly WITH LOGIN PASSWORD '${READONLY_PWD_SQL}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE apidb TO worker, readonly;
GRANT USAGE ON SCHEMA public TO worker, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO worker;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO worker;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO worker;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO worker;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO readonly;
EOF
