#!/bin/sh
set -e

WORKER_PWD=$(cat /run/secrets/user_pwd)
READONLY_PWD=$(cat /run/secrets/readonly_pwd)

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
CREATE ROLE worker LOGIN PASSWORD '${WORKER_PWD}';
CREATE ROLE readonly LOGIN PASSWORD '${READONLY_PWD}';

GRANT CONNECT ON DATABASE $POSTGRES_DB TO worker, readonly;
GRANT USAGE ON SCHEMA public TO worker, readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO worker;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO worker;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
EOF
