#!/bin/sh

set -e

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<EOF
CREATE ROLE user LOGIN PASSWORD '$(cat /run/secrets/user_pwd)';
CREATE ROLE readonly LOGIN PASSWORD '$(cat /run/secrets/readonly_pwd)';

GRANT CONNECT ON DATABASE $POSTGRES_DB TO user, readonly;
GRANT USAGE ON SCHEMA public TO user, readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
EOF
