services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d 
            - ./backup:/backup
            - ./logs:/var/log/postgresql
            - ./postgres.conf:/etc/postgresql/postgresql.conf
        ports:
            - "5432:5432"
        networks:
            - site
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    postgres_data:
        driver: local

networks:
    site:
        external: true
